-- ============================================================
-- Лабораторная №4. Часть 1–2: подготовка Primary
-- Запуск: docker exec -i internshipservice-postgres-1 psql -U postgres -d postgres < 01_setup_primary.sql
-- ============================================================

-- 1. Пользователь для streaming replication
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'replicator') THEN
        CREATE ROLE replicator WITH LOGIN REPLICATION PASSWORD 'replica_password_123';
    END IF;
END
$$;

SELECT rolname, rolreplication, rolcanlogin FROM pg_roles WHERE rolname = 'replicator';

-- 2. Реальная сущность сервиса: заявки (applications)
CREATE TABLE IF NOT EXISTS applications (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id integer  NOT NULL,
    vacancy_id   integer  NOT NULL,
    status       smallint NOT NULL DEFAULT 0,
    applied_date timestamptz NOT NULL DEFAULT now(),
    cover_letter text
);

CREATE INDEX IF NOT EXISTS idx_applications_candidate_id ON applications (candidate_id);
CREATE INDEX IF NOT EXISTS idx_applications_vacancy_id   ON applications (vacancy_id);

INSERT INTO applications (candidate_id, vacancy_id, status, applied_date, cover_letter)
SELECT
    (g % 50) + 1,
    (g % 20) + 1,
    (g % 4),
    now() - (g || ' minutes')::interval,
    'Seed application #' || g
FROM generate_series(1, 1000) AS g
WHERE NOT EXISTS (SELECT 1 FROM applications LIMIT 1);

SELECT count(*) AS applications_on_primary FROM applications;

-- 3. Проверка настроек репликации на Primary
SHOW wal_level;
SHOW max_wal_senders;
SHOW max_replication_slots;
SELECT * FROM pg_replication_slots;
