create table if not exists users (
    id bigint primary key generated by default as identity,
    username text not null unique,
    email text not null unique,
    password text not null,
    role text not null default 'Candidate' check (role in ('Admin', 'Company', 'Candidate')),
    created_at timestamp default current_timestamp
);

create index if not exists idx_users_email on users(email);
create index if not exists idx_users_username on users(username);

