create table if not exists companies (
    id bigint primary key generated by default as identity,
    name text not null,
    description text,
    website text,
    email text not null,
    phone text,
    created_date timestamp default current_timestamp
);

create index if not exists idx_companies_email on companies(email);

