create table if not exists candidates (
    id bigint primary key generated by default as identity,
    first_name text not null,
    last_name text not null,
    email text not null,
    phone text,
    resume_url text,
    skills text,
    experience_level integer check (experience_level in (0, 1, 2))
);

create index if not exists idx_candidates_email on candidates(email);

