create table if not exists tags (
    id bigint primary key generated by default as identity,
    name text not null unique,
    category integer not null check (category in (0, 1, 2))
);

create index if not exists idx_tags_category on tags(category);

