create table if not exists vacancies (
    id bigint primary key generated by default as identity,
    title text not null,
    description text,
    requirements text,
    salary_range text,
    type integer not null check (type in (0, 1)) default 0,
    location text,
    is_active boolean not null default true,
    created_date timestamp default current_timestamp,
    company_id bigint not null references companies(id) on delete cascade
);

create index if not exists idx_vacancies_company_id on vacancies(company_id);
create index if not exists idx_vacancies_type on vacancies(type);
create index if not exists idx_vacancies_is_active on vacancies(is_active);
create index if not exists idx_vacancies_created_date on vacancies(created_date);

