create table if not exists applications (
    id bigint primary key generated by default as identity,
    candidate_id bigint not null references candidates(id) on delete cascade,
    vacancy_id bigint not null references vacancies(id) on delete cascade,
    status integer not null check (status in (0, 1, 2, 3)) default 0,
    applied_date timestamp default current_timestamp,
    cover_letter text,
    unique(candidate_id, vacancy_id)
);

create index if not exists idx_applications_candidate_id on applications(candidate_id);
create index if not exists idx_applications_vacancy_id on applications(vacancy_id);
create index if not exists idx_applications_status on applications(status);
create index if not exists idx_applications_applied_date on applications(applied_date);

