create table if not exists api_keys (
    id bigint primary key generated by default as identity,
    key text not null unique,
    expiration timestamp not null,
    is_active boolean not null default true
);

create index if not exists idx_api_keys_key on api_keys(key);
create index if not exists idx_api_keys_is_active on api_keys(is_active);

