create schema if not exists lab;

alter table applications rename to applications_legacy;

create table applications (
    id bigint generated by default as identity,
    candidate_id bigint not null references candidates(id) on delete cascade,
    vacancy_id bigint not null references vacancies(id) on delete cascade,
    status integer not null default 0 check (status in (0, 1, 2, 3)),
    applied_date timestamp not null default current_timestamp,
    cover_letter text,
    primary key (id, applied_date),
    unique (candidate_id, vacancy_id, applied_date)
) partition by range (applied_date);

create table applications_2025_10 partition of applications
    for values from ('2025-10-01') to ('2025-11-01');
create table applications_2025_11 partition of applications
    for values from ('2025-11-01') to ('2025-12-01');
create table applications_2025_12 partition of applications
    for values from ('2025-12-01') to ('2026-01-01');
create table applications_2026_01 partition of applications
    for values from ('2026-01-01') to ('2026-02-01');
create table applications_2026_02 partition of applications
    for values from ('2026-02-01') to ('2026-03-01');
create table applications_2026_03 partition of applications
    for values from ('2026-03-01') to ('2026-04-01');
create table applications_2026_04 partition of applications
    for values from ('2026-04-01') to ('2026-05-01');
create table applications_2026_05 partition of applications
    for values from ('2026-05-01') to ('2026-06-01');
create table applications_2026_06 partition of applications
    for values from ('2026-06-01') to ('2026-07-01');
create table applications_2026_07 partition of applications
    for values from ('2026-07-01') to ('2026-08-01');
create table applications_2026_08 partition of applications
    for values from ('2026-08-01') to ('2026-09-01');
create table applications_2026_09 partition of applications
    for values from ('2026-09-01') to ('2026-10-01');
create table applications_2026_10 partition of applications
    for values from ('2026-10-01') to ('2026-11-01');
create table applications_2026_11 partition of applications
    for values from ('2026-11-01') to ('2026-12-01');
create table applications_2026_12 partition of applications
    for values from ('2026-12-01') to ('2027-01-01');
create table applications_default partition of applications default;

insert into applications (id, candidate_id, vacancy_id, status, applied_date, cover_letter)
select id, candidate_id, vacancy_id, status, coalesce(applied_date, current_timestamp), cover_letter
from applications_legacy;

select setval(
    pg_get_serial_sequence('applications', 'id'),
    coalesce((select max(id) from applications), 1)
);

drop table applications_legacy;

create index if not exists idx_applications_candidate_id on applications(candidate_id);
create index if not exists idx_applications_vacancy_id on applications(vacancy_id);
create index if not exists idx_applications_status on applications(status);
create index if not exists idx_applications_applied_date on applications(applied_date);
create index if not exists idx_applications_candidate_applied_date
    on applications (candidate_id, applied_date desc);
